### ISSUE TITLE
libpixyusb_swig python bindings not working in linux

### ISSUE THREAD

**Issue by illuusio** [charmedlabs/pixy#16]
Python example is not working in Linux (haven't tested yet in Mac OS X). After little digging it seems that there is something wrong in USBlink stuff because it fails in sendFull method.

**Comment by richlegrand** [comment]
Hi Tuukka,
You should update to the latest libusb version.  We've found issues with
older versions.

thanks,
---rich

On Thu, Mar 19, 2015 at 5:26 AM, Tuukka Pasanen <notifications@github.com>
wrote:

> Python example is not working in Linux (haven't tested yet in Mac OS X).
> After little digging it seems that there is something wrong in USBlink
> stuff because it fails in sendFull method.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charmedlabs/pixy/issues/16>.
>



-- 
Charmed Labs
www.charmedlabs.com

**Comment by illuusio** [comment]
hmm..I'm using release 1.0.19 should I use some GIT version of libusb?

**Comment by richlegrand** [comment]
What does the issue look like?  are you not getting any data whatsoever?

Make sure that libpixyusb works by running the hello_pixy example.  Make
sure this works before trying the python wrappers.

thanks,
--rich

On Thu, Mar 19, 2015 at 8:12 AM, Tuukka Pasanen <notifications@github.com>
wrote:

> hmm..I'm using release 1.0.19 should I use some GIT version of libusb?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charmedlabs/pixy/issues/16#issuecomment-83557430>.
>



-- 
Charmed Labs
www.charmedlabs.com

**Comment by illuusio** [comment]
Yes PixyMon and hello_pixy is working as expected. I digged little bit and first problem was in:
pixyintepreter.cpp line 134 when return doesn't open mutex because of an errornous return (https://github.com/charmedlabs/pixy/blob/master/src/host/libpixyusb/src/pixyinterpreter.cpp#L134) not a biggy but thread get stuck and no error was returned.
Everything goes smoot until we hit USBLink::send (which return -7 which seems to be timeout) first time called by
<pre>
pixydebug: Chirp::Chirp()
pixydebug: Chirp::Chirp() returned
pixydebug: Chirp::setLink()
</pre>
It's also slow if you compare to hello_pixy to init so could it be just time out problem?

**Comment by 0xA1** [comment]
Nice catch. Looks like we forgot to release a mutex.

Try this latest commit: https://github.com/charmedlabs/pixy/commit/a3ce86be9d4381a21270445212c0b1235cdefc83

**Comment by richlegrand** [comment]
Thanks john :)

On Friday, March 20, 2015, John Leimon <notifications@github.com> wrote:

> Nice catch. Looks like we forgot to release a mutex.
>
> Try this latest commit: a3ce86b
> <https://github.com/charmedlabs/pixy/commit/a3ce86be9d4381a21270445212c0b1235cdefc83>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/charmedlabs/pixy/issues/16#issuecomment-84084886>.
>


-- 
Charmed Labs
www.charmedlabs.com
