### ISSUE TITLE
Failed to retrieve Pixy firmware version. Pixy Error: Invalid command

### ISSUE THREAD

**Issue by afwilkin** [charmedlabs/pixy#42]
![image](https://user-images.githubusercontent.com/16963678/163693908-7880384e-0adc-4fa6-a36a-1491e371db0d.png)

I am getting this issue on Ubuntu 20.04.3 running in vmware. 
I am not getting this issue when running on Ubuntu 20.04.3 installed directly on metal. 

I thought it might be a permissions issue, but like I said it works when installed on an OS running directly on my laptop. 
I am going to continue checking out what is going on, but I thought I would post here if anyone has any insight. Thank you!

**Comment by johnleimon** [comment]
Hi Andrew,

If you are getting an issue in VMWARE but not bare metal, then your issue
is most likely with your VMWARE configuration, deployment, etc.

Think algebra.  Isolate and identify.

Good luck

**Comment by afwilkin** [comment]
Totally. I was attempting to do that.
My confusion came with the fact that all my other USB passthroughs are working, lsusb is listing the device correctly, and hello_pixy is able to identify when the USB is plugged in or not.

The difficult thing is....why is it not able to detect the firmware. 

Is there a known situation where the pixy camera can be detected but asking for the firmware version not yield a response?

**Comment by johnleimon** [comment]
Andrew,

Start with something that works and build from there.  Create a "sandbox"
if you will to experiment with.

Figure it out. One. Step. At. A. Time.

John

**Comment by afwilkin** [comment]
Ok. Was just posting on here to see if there was a direction I could be pointed in to get started. But thanks for the pep talk Tony Robinson
